resources:
- name: game-monitor-repo
  type: git
  source:    
    uri: {{pipeline-git-uri}}
    branch: {{pipeline-git-branch}}

jobs:
- name: game-monitor-job
  plan:
  - get: game-monitor-repo
  - task: task_build-dotnet
    file: game-monitor-repo/ci/task-build-dotnet.yml