resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource
    tag: latest


resources:
- name: game-monitor-repo
  type: git
  icon: github
  source:    
    uri: {{pipeline-git-uri}}
    branch: {{pipeline-git-branch}}
- name: file-repository
  type: artifactory
  source:
    endpoint: {{artifactory-uri}}
    repository: {{artifactory-repository}}
    username: {{artifactory-username}}        
    password: {{artifactory-password}}

jobs:
- name: game-monitor-job
  plan:
  - get: game-monitor-repo
    trigger: true
  - task: task_build-dotnet
    file: game-monitor-repo/ci/task-build-dotnet.yml
  - put: file-repository
    params:      
      file: ./*
      #file: Output/GameMonitor.zip